### PR TITLE
prevent no folder error

### PR DESCRIPTION
**Pull request by wasdee**

### CODE REVIEW

**Comment by balupton** [comment]
Interesting. Was this error countered in trial mode? As via `dorothy install` these should have already been setup.

**Comment by wasdee** [comment]
> Interesting. Do you recall the steps you took to encounter this error? Was it via running `setup-util-nu` in trial mode? As via the install method, the user configuration should have already been setup by `dorothy install`

I found this when I ran `bash -ic "$(curl -fsSL https://dorothy.bevry.me/install)"` on newly install WSL2, Ubuntu

**Comment by balupton** [comment]
Was able to reproduce. Shocking.

Will fix this up over the coming days, and make sure that our tests catch such things in the future — I'm surprised they didn't catch this!

**Comment by balupton** [comment]
Went with an alternative approach that will still enable the custom user configuration flow. Seems fixed now. Hope you enjoy Dorothy, sorry for the inconvenience! Thank you so much for reporting.

**Pull request closed without merging**
