### PR TITLE
fix editor selection in Dorothy command for vscode

### PR DESCRIPTION
**Pull request by wasdee**

### CODE REVIEW

**Comment by balupton** [comment]
Strange this was necessary for you.

Without a `--gui` or `--terminal` flag, it should autodetect based on whether our environment is desktop or headless. For instance, if we are sshing into a desktop machine target, we don't want to open vscode on the target.

The change of else to else if, is also surprising, as from memory it should be only one or the other; I could be wrong here though, as could be some exceptions.

I'm guessing the autodetection did not work.

Which desktop and terminal were you using?

**Comment by wasdee** [comment]
this is what i got after `dorothy edit`
it ran `nano`.
image
image

# context 
- on vscode Windows 11 with remote connection to WSL2

**Comment by wasdee** [comment]
> Strange this was necessary for you.
> 
> Without a `--gui` or `--terminal` flag, it should autodetect based on whether our environment is desktop or headless. For instance, if we are sshing into a desktop machine target, we don't want to open vscode on the target.
> 
> The change of else to else if, is also surprising, as from memory it should be only one or the other; I could be wrong here though, as could be some exceptions.
> 
> I'm guessing the autodetection did not work.
> 
> Which desktop and terminal were you using?

maybe it detect that im on a ssh

**Comment by balupton** [comment]
Ahhh, yeah that will be it. Should be easy to reproduce, I'll fix it up when I get home.

**Pull request closed without merging**
